name: photocoa
description: Temporary photos app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.10.1
  get_it: ^7.2.0
  provider: ^6.0.5
  audioplayers: ^2.0.0
  path_provider: ^2.0.11
  path: ^1.8.2
  native_exif: ^0.4.0
  intl: ^0.17.0
  numberpicker: ^2.1.1
  package_info: ^2.0.2
  url_launcher: ^6.1.7
  flutter_native_splash: ^2.2.16
  image: ^3.3.0
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/sound/"
    - "assets/icons/"

flutter_native_splash:
  color: "#ff5722"
  image: "assets/icons/cocoa_icon.png"

flutter_icons:
  android: true
  image_path: "assets/icons/cocoa_icon.png"
  background_color: "#ff5722"
  icon_size: 48